# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, null=True)),
                ('serial_number', models.CharField(max_length=255, null=True)),
                ('brand_name', models.CharField(max_length=255, null=True)),
                ('number_of_usb_ports', models.IntegerField(null=True)),
                ('hard_drive', models.IntegerField(null=True)),
                ('ram', models.IntegerField(null=True)),
                ('is_wifi_enabled', models.BooleanField(default=False)),
                ('sound_system', models.CharField(max_length=255, null=True)),
                ('cpu_speed', models.FloatField(null=True)),
            ],
        ),
    ]
